### ISSUE TITLE
mecab-config: command not found error while installing on mac

### ISSUE THREAD

**Issue by jiterika** [Kensuke-Mitsuzawa/JapaneseTokenizers#55]
Hi,

Thank you for making this package available, when i try to install i get the following error. Please let me know how i can resolve it

Collecting mecab-python3
  Using cached https://files.pythonhosted.org/packages/ac/48/295efe525df40cbc2173748eb869290e81a57e835bc41f6d3834fc5dad5f/mecab-python3-0.996.1.tar.gz
    Complete output from command python setup.py egg_info:
    /bin/sh: mecab-config: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/rd/qqy1bpm93qj1qcmrj8624qz91pyzr5/T/pip-build-pqo_16ve/mecab-python3/setup.py", line 29, in <module>
        inc_dir  = mecab_config("--inc-dir")
      File "/private/var/folders/rd/qqy1bpm93qj1qcmrj8624qz91pyzr5/T/pip-build-pqo_16ve/mecab-python3/setup.py", line 27, in mecab_config
        return os.popen("mecab-config " + arg).readlines()[0].split()
    IndexError: list index out of range

Thank You

**Comment by Kensuke-Mitsuzawa** [comment]
Hi. Thanks for your report.
As high probability, you might be failed to make install mecab, which is tokenizer library written in C++.

This line of error message shows that.

```
inc_dir = mecab_config("--inc-dir")
```

That's means, you couldn't call `mecab-config` command with `--inc-dir` option.

Please make sure, you could call `mecab` command and `mecab-config` command.

If it's not working, you are supposed to make install them first.

**Comment by jiterika** [comment]
Hi,
Thank you for the reply.

"Please make sure, you could call `mecab` command and `mecab-config` command.

If it's not working, you are supposed to make install them first."

how can i install, when i tried to install by downloading the package and running 
python setup.py install as mentioned in the installation instructions, i got the above error message.

Thank You

**Comment by Kensuke-Mitsuzawa** [comment]
Hi. Mecab is completely different from Python world. So, you couldn't make install with python package.

Please refer here to know a procedure for installation.
https://github.com/Kensuke-Mitsuzawa/JapaneseTokenizers/blob/master/README.md#mecab

I guess you could make it all with `brew install mecab` if you're familiar with `brew` which is a package manager for Mac. However, I'm not sure because I don't have any Mac laptop now.

**Comment by jiterika** [comment]
Hi,

Thank you. It worked.
