### ISSUE TITLE
Error when loading MecabWrapper

### ISSUE THREAD

**Issue by bigredbug47** [Kensuke-Mitsuzawa/JapaneseTokenizers#58]
Hi Kensuke Mitsuzawa,

I occurred some errors when using JapaneseTokenizer. I have installed package by make command (both) make command.

Here is the error when I run code: 
`mecab_wrapper = JapaneseTokenizer.MecabWrapper(dictType='ipadic')`

![image](https://user-images.githubusercontent.com/31086329/62366026-ede89f80-b54f-11e9-9a2e-121bc5d1dfba.png)

Please let me know where I was wrong. Thank you very much.

**Comment by Kensuke-Mitsuzawa** [comment]
@bigredbug47 Hello. Thank you for using this package.
The package seems to say that you have not installed Mecab correctly yet.

Could you try this command in your bash(or zsh something) and tell me the result?

```
echo "きょうはいい天気です" | mecab
```

The result should be the below.

```
きょう	名詞,副詞可能,*,*,*,*,きょう,キョウ,キョー
は	助詞,係助詞,*,*,*,*,は,ハ,ワ
いい	形容詞,自立,*,*,形容詞・イイ,基本形,いい,イイ,イイ
天気	名詞,一般,*,*,*,*,天気,テンキ,テンキ
です	助動詞,*,*,*,特殊・デス,基本形,です,デス,デス
EOS
```

If you don't get this result, you have not installed mecab yet.

There might be some bug in my Make command.

Still, you could try installing it manually.
Please see here for further information.
https://github.com/Kensuke-Mitsuzawa/JapaneseTokenizers#mecab-1

**Comment by bigredbug47** [comment]
I have installed successfully, maybe some of my libraries conflict with your.
I have create a new environment and install follow your instruction, it works like a charm.
Thank you very much
